//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covid_19_WebSite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class COVID_19_DBEntities : DbContext
    {
        public COVID_19_DBEntities()
            : base("name=COVID_19_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Enumeration> Enumerations { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<RegionStatistique> RegionStatistiques { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Role_Util> Role_Util { get; set; }
        public virtual DbSet<Test> Tests { get; set; }
        public virtual DbSet<Utilisateur> Utilisateurs { get; set; }
        public virtual DbSet<Ville> Villes { get; set; }
    }
}
