//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covid_19_WebSite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Enumeration
    {
        public string UID { get; set; }
        [Display(Name = "Cas Mort")]
        public Nullable<int> Cas_Mort { get; set; }
        [Display(Name = "Cas Rétablis")]
        public Nullable<int> Cas_Retablis { get; set; }
        [Display(Name = "Cas Confirmer")]
        public Nullable<int> Cas_Confirmer { get; set; }
        [Display(Name = "Date")]
        public Nullable<System.DateTime> Date_Ins { get; set; }
        public string UID_V { get; set; }
    
        public virtual Ville Ville { get; set; }
    }
}
